### ISSUE TITLE
Possible to fix links? I moved the database to a new workspace and tried to reconnect it 

### ISSUE THREAD

**Issue by do-not-perceive-me** [dvanoni/notero#134]
**Describe the issue**
I moved my database to a different workspace, realized that it needed a new integration, and using Notero with the new integration. This didn't work and created duplicates of all the items. 

I restored the database in original workspace and tried to reconnect Notero. This also made duplicates. 

Is there a way to reset the links in Notero without copying and pasting them all?

**Comment by dvanoni** [comment]
@do-not-perceive-me, thanks for describing your issue. Would it be feasible to recreate the database in the new Notion workspace instead of copying over the existing database from the old workspace? Or do you have additional data associated with the old database that would be lost?

If you are able to create a fresh database in the new workspace, then I think you can maybe use the [bulk sync](https://github.com/dvanoni/notero#how-to-bulk-sync-existing-items) approach to re-sync all of your Zotero items into the new database. I believe that would then update all of the existing links in Zotero to point to the pages in the new database.

**Comment by do-not-perceive-me** [comment]
The issue is that I have additional properties and notes within the original database. When I make a brand new database, they are all linked Zotero, but I've lost the page notes and other info. 

Right now I've kept the duplicates and been slowly copying over the properties to the new/linked items but that's obviously a bit inconvenient. 

I think in the future, I would make the Zotero linked database, and then relate those database items to a different database for writing notes or sorting them. 

I'm not sure how easy it is to implement, but it would be really useful if you could manually change the Notion link in the Zotero item

**Comment by do-not-perceive-me** [comment]
That's great! Thanks so much for the tutorial. I had tried to edit the existing link, but didn't think to delete it and add a new one.
