### ISSUE TITLE
CHROME Manifest file is missing or unreadable Could not load manifest.

### ISSUE THREAD

**Issue by lorenzoleandro** [dvanoni/notero#142]
the Chrome manifest does not load properly and I cannot install the extension on Chrome

**Comment by dvanoni** [comment]
Hi @lorenzoleandro, thanks for reaching out.

Notero is a [plugin for Zotero](https://www.zotero.org/support/plugins) rather than Chrome. You can find [installation instructions](https://github.com/dvanoni/notero#install-and-configure-notero-plugin) in the README that describe how to install it in Zotero.

Let me know if you have any more questions!
