### ISSUE TITLE
Read"/read,/unread,/done" tags to the reading status 

### ISSUE THREAD

**Issue by sheldon123z** [dvanoni/notero#184]
Hi, 
First of all, Notero is a wonderful add-on for the zotero software. I wonder if it is possible to read some specific tags like "/read,/unread,/done" or any other personal defined tags into the reading status filed in the notion tamplate? since I also use some other nice add-ons which can generate the tags automatically in zotero, it is really hard to manage two pipelines while they have the same functions, and i think if this can be achieved, many other problems can be solved.
thanks!

**Comment by dvanoni** [comment]
Hi, @sheldon123z! Since tags are already synced into Notion, I think you might be able to achieve what you're looking for using a **formula** property. 

For example, I created a formula property called `Reading Status` with the following formula:

```js
if(contains(prop("Tags"), "unread"), "Unread", if(contains(prop("Tags"), "read"), "Read", if(contains(prop("Tags"), "done"), "Done", "")))
```

It's a little clunky, and you have to be careful with the order that you write your formula in so that it doesn't return the wrong value if the text of one of the tags is a subset of another. For example, `read` is a subset of `unread` above, so we need to check for `unread` _before_ `read`.

But if you're okay with that approach, this is what you can do with it!

https://user-images.githubusercontent.com/299357/205236308-c2977c88-7cc9-4165-b74e-c1aec948c493.mp4

**Comment by sheldon123z** [comment]
Hi @dvanoni ,

Thank you very much, I tried the method and it successed ! This is very useful for me to know exactly what acticles that I have read, and also it helps me to make more personal categories ! Thank you and the issue is closed! 

That's my current setting, I'm using a add-on called zotero IF pro max, which has the function for automatically inserting /read,/unread,/Done tags,  and the notion help me to categorize them into different columns using your method :) cheers!


![image](https://user-images.githubusercontent.com/42455304/205444529-af779e79-84a5-4218-a259-46b79a74e30f.png)
