### ISSUE TITLE
APIResponseError: query failed validation

### ISSUE THREAD

**Issue by bluebirdthrone** [dvanoni/notero#217]
Hello, Thank you so much for creating this plug-in. It has been somthing I have been looking for for a while now! 

I installed it as per the instructions, (I think), but when I try to sync specific items to Notion, I get an error "APIResponseError: query failed validation..." (screenshot attached). I am guessing I am doing something wrong with the database in Notion (screenshot attached - PS: I have pre-existing entries in the database that I have been entering manually for a while now), but cannot figure it out. Help would be appreciated! 

<img width="280" alt="Screenshot 2023-01-31 at 6 21 54 PM" src="https://user-images.githubusercontent.com/99138619/215764973-56e0f039-38a4-437f-8f34-e22ab9b903e8.png">

<img width="1112" alt="Screenshot 2023-01-31 at 6 23 35 PM" src="https://user-images.githubusercontent.com/99138619/215765340-8b814641-e05a-40c0-92cb-aee6599b6833.png">
<img width="1094" alt="Screenshot 2023-01-31 at 6 23 55 PM" src="https://user-images.githubusercontent.com/99138619/215765397-631fd317-b02d-4e81-add7-a4d6416cdf8c.png">

Also attaching screenshot of Notero preferences. 
<img width="487" alt="Screenshot 2023-01-31 at 6 24 38 PM" src="https://user-images.githubusercontent.com/99138619/215765635-82828501-d644-4b98-be4e-fbc5464dbd23.png">

**Comment by dvanoni** [comment]
Hi, @bluebirdthrone! Thanks for sharing those screenshots.

The issue is that you have some extra characters in the **Database ID** field that shouldn't be there. It should contain only the first part up to (and not including) `?v=`. So, it should just be `b3ffb2c3ebfb40bf9232d528d32e16e1`. Let me know if that works for you!

Also, to keep your Notion database safe, I'd recommend creating a new integration token so that an attacker can't use the one visible in your screenshot. You can get a new token by going to the page where you created your Notion integration and clicking the **Refresh** button on the integration token field.

**Comment by bluebirdthrone** [comment]
Thank you! This is now working perfectly! And yes, I will change the integration token. Thank you for the heads up!
