### ISSUE TITLE
Error when collection or tag name exceeds Notion length limit

### ISSUE THREAD

**Issue by cleovalentine** [dvanoni/notero#240]
Amazing tool, thank you so much! I am having an API Response Error: body failed validation. Any Ideas what this means? I have attached a screenshot. Thanks in advance!
<img width="143" alt="Screenshot 2023-03-21 at 2 34 43 PM" src="https://user-images.githubusercontent.com/39169638/226641369-9d31ea0c-bca7-4d6c-b91f-0f0c44631f9a.png">

**Comment by dvanoni** [comment]
Hi @cleovalentine, thanks for reporting this!

I believe what's happening here is that Notero is trying to sync a value for the `Collections` multi-select property that is longer than what the Notion API supports. This can happen if a Zotero item is nested in collections such that the concatenation of the collection names (joined with ` ▸ `) is longer than 100 characters.

For example, with the item in the screenshot below, we'll end up trying to create a multi-select option with the following name that ends up being 117 characters:

    This name has 27 characters ▸ This name has 27 characters ▸ This name has 27 characters ▸ This name has 27 characters

![CleanShot 2023-03-21 at 23 31 54@2x](https://user-images.githubusercontent.com/299357/226821125-37021f75-2c55-4fd8-a331-a92156d89126.png)

Does this seem to describe what you have in Zotero? If so, a quick (though admittedly not great) workaround would be to either remove a layer of nesting in your collections or shorten the names of some of the collections.

For a proper fix, it looks like we'll need to truncate the value to at most 100 characters. I could add ellipses to the end of anything longer than 100 characters, but I wonder if it'd make more sense to add the ellipses somewhere in the middle since the end would be the most deeply nested collection and thus the most "precise" part of the name. Do you have any thoughts on that?

**Comment by Bachery** [comment]
Encountered same issue for Tags:
```
APIResponseError: body failed validation:
body.properties.Tags.multi_select[1].name.length should be <= `100`
```
I fix it by deleting the long tags manually

**Comment by SofiCourtney** [comment]
Hi! I'm having the same issue as @cleovalentine. I tried removing layers of nesting, and shortening the names of collections, but I'm still getting the same error (with the same amount of characters). Any clue what's going on here?
<img width="263" alt="Screen Shot 2023-04-18 at 2 02 56 PM" src="https://user-images.githubusercontent.com/97610963/232875926-92284f9b-4614-4e62-82a3-ad4bf40d103c.png">

**Comment by dvanoni** [comment]
Hi @SofiCourtney! It sounds like you've done everything I'd suggest, so to help me figure out what's still going on I'll need to get some more logs from you.

If you're up for it, would you mind installing [this test build](https://nightly.link/dvanoni/notero/actions/runs/4728509773/notero-0.4.7-94.zip) that enables more logging and then send me a screenshot of the output in the error console when you try to sync an item? The below video shows how to find the logs in the error console.

Thanks!

https://user-images.githubusercontent.com/299357/232671668-6a892763-ce41-4d6b-b5cd-6a406578b2a1.mp4

**Comment by SofiCourtney** [comment]
Hi David

Yes, I can do  that, but I’m having a bit of an issue installing the test build- I expected there to be a .xpi file that I can add to zotero using the ‘add on’ menu. How do I install this version with the .rdf file?

Thank you!

From: David Hoff-Vanoni ***@***.***>
Date: Tuesday, April 18, 2023 at 9:42 PM
To: dvanoni/notero ***@***.***>
Cc: Sofi F Courtney ***@***.***>, Mention ***@***.***>
Subject: Re: [dvanoni/notero] API Response Error: body failed validation (Issue #240)

Hi @SofiCourtney<https://urldefense.com/v3/__https:/github.com/SofiCourtney__;!!K-Hz7m0Vt54!koh-i_uG-WeO_a3OJzk9rzyC-uzavWmh-HZytAcVGuAktFoaC0pK5GVF2yQPN1DLTx5OK90udIA0rSkafvwqrp0$>! It sounds like you've done everything I'd suggest, so to help me figure out what's still going on I'll need to get some more logs from you.

If you're up for it, would you mind installing this test build<https://urldefense.com/v3/__https:/nightly.link/dvanoni/notero/actions/runs/4728509773/notero-0.4.7-94.zip__;!!K-Hz7m0Vt54!koh-i_uG-WeO_a3OJzk9rzyC-uzavWmh-HZytAcVGuAktFoaC0pK5GVF2yQPN1DLTx5OK90udIA0rSkaEsWTgDs$> that enables more logging and then send me a screenshot of the output in the error console when you try to sync an item? The below video shows how to find the logs in the error console.

Thanks!

https://user-images.githubusercontent.com/299357/232671668-6a892763-ce41-4d6b-b5cd-6a406578b2a1.mp4<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/299357/232671668-6a892763-ce41-4d6b-b5cd-6a406578b2a1.mp4__;!!K-Hz7m0Vt54!koh-i_uG-WeO_a3OJzk9rzyC-uzavWmh-HZytAcVGuAktFoaC0pK5GVF2yQPN1DLTx5OK90udIA0rSka67kNA3s$>

**Comment by dvanoni** [comment]
Hi @SofiCourtney, I forgot to mention that the test builds are named as `.zip` instead of `.xpi`, but they work the same way. Meaning, you don't want to extract the files from the `.zip` but instead install the entire `.zip` the same way you do with a `.xpi`.

Let me know if that works!

**Comment by SofiCourtney** [comment]
<img width="1240" alt="Screen Shot 2023-04-19 at 10 59 26 AM" src="https://user-images.githubusercontent.com/97610963/233116825-8a7258ab-6d58-4981-9f2a-f79bcff6197f.png">

**Comment by dvanoni** [comment]
Thanks for sending that, @SofiCourtney! It looks like the collection that's causing trouble is the following:

> Main search ▸ databases searched ▸ Natural Science Collection Search ▸ Abstract screen ▸ included ▸ fire

You'll need to either remove some nesting or shorten one of the collection names.

I hope to get a proper fix in for this soon, but let me know if you're able to work around it for now!

**Comment by dvanoni** [comment]
I see in your screenshot that the item being synced is in 5 different collections. I see that `Full text ▸ fire` is one of them, but it's the collections under `Main search` that appear to be causing the issue. Can you shorten the collections under `Main search` to see if that helps?
