### ISSUE TITLE
Changing database ID does not work

### ISSUE THREAD

**Issue by dkamaitis** [dvanoni/notero#241]
**Describe the issue**
Changing Database ID to a new one does not work. Notero still tries to sync using the old Notion Database ID.

**To Reproduce**

1. Create/copy Notion database.
2. Paste new Database ID into Notero preferences.
3. Sync any enabled collection.
4. See changes in the old Notion database.

**Expected behavior**
Changes synced to a new Notion database.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by dvanoni** [comment]
Hi @dkamaitis, thanks for reporting this issue!

I see what's happening here. When a Zotero item has been synced to Notion, a link to the Notion page is saved in Zotero so that any future updates to the item will update the same page in Notion instead of creating a new page. Unfortunately, there's currently no logic to check that the page is still in the database specified by the database ID in the Notero preferences.

I'd like to implement a proper fix for this, but in the meantime, here are some workarounds I can think of:

- Delete the "Notion" links attached to synced Zotero items and then sync again.
- Delete the pages in the old Notion database and then sync again. You have to _permanently_ delete the pages in order for this to work—i.e. you have to delete the pages from the **Trash**.
   - I think the easiest way to do this is to bulk delete the pages from a table view of your database, and then navigate to the "In current page" view of the Trash to find the pages to permanently delete.
   - See this [Notion documentation](https://www.notion.so/help/duplicate-delete-and-restore-content#find-pages-in-trash) for more details.

**Comment by dkamaitis** [comment]
Hi @dvanoni, thanks for the detailed explanation - very much appreciate your work on Notero.
