### ISSUE TITLE
The synronization fills only the "name" and not the other columns (type, authors, year, etc.).

### ISSUE THREAD

**Issue by fmoensdehase** [dvanoni/notero#257]
When I add a reference in Zotero to the folder I have intended for Notion synchronization, the reference is synchronized, but only filling in the "name" column, and not the other database columns (type, title, authors, year). 

Do you know how could I solve this problem? 

![image](https://user-images.githubusercontent.com/132091362/235211746-5b071c9c-1324-4054-b924-7a50d4493641.png)

![image](https://user-images.githubusercontent.com/132091362/235211792-8b2a566a-2bbd-4ecf-85aa-0e121798146b.png)

**Comment by dvanoni** [comment]
Hi @fmoensdehase, this problem is occurring because Notero currently only supports English property names (the exact ones listed in the readme). Unfortunately, for now, you'll have to change your database properties to English in order for the values to sync.

One of the improvements I'm planning for the future is to allow the property names to be configurable so that you can name them however you'd like.
