### ISSUE TITLE
TypeError: style.getCiteProc is not a function

### ISSUE THREAD

**Issue by lenadelaloire** [dvanoni/notero#258]
Hi! First of all - thank you SO MUCH for creating this amazing tool. 
I've been using Notero on my old Mac for a few months and all was going swimmingly. I've just gotten a new Mac, and for the life of me cannot figure out why I can't get Notero to work. Any help would be appreciated - I'm starting my Master's next week and Notero is just such a lifesaver!

The error I'm getting is:
<img width="294" alt="Screenshot 2023-04-29 at 9 43 41 AM" src="https://user-images.githubusercontent.com/54654393/235304050-0c5e0365-20ae-45f0-97f9-d4a32b7da010.png">
TypeError: style.getCiteProc is not a function

I have:
1. Tried using my original database and integration.
2. Deleted the old integration and created a new one.
3. Created a new blank database (advanced from the template) which was the same template I used for my last database.
4. Uninstalled and reinstalled the add-on, updated all info, shared my database to the integration, etc. 
5. Tried different types of citations, media types, etc. 

This happens any time I add something new to Zotero, or if I grab an old saved article and "Sync to Notion". I've also tried deleting the link attachments from my old database and then sharing, nothing. I cannot get anything to sync over into Notion. Where am I going wrong here?

Info:
Zotero: 6.0.26 (old computer had 6.0.23 - could this be a thing?)
Notion: 2.1.15 (same on old)
Notero: 0.4.6 (same on old)
My new computer has the M2 chip where my old one was Intel. I'm not super tech savvy, don't know if that would make a difference?

Thank you in advance!

**Comment by dvanoni** [comment]
Hi @lenadelaloire, thanks for reaching out and sharing so much info!

Some other folks ran into this issue previously in #12. The original issue we discovered was fixed by ensuring the `American Psychological Association 7th edition` style was installed. Can you open the **Cite** preferences in Zotero and confirm that it's installed? If it's not, you can either download it from https://www.zotero.org/styles/apa or click the **Get additional styles...** link and search for it in the window that opens.

Let me know if this helps at all!

![CleanShot 2023-04-29 at 08 32 02@2x](https://user-images.githubusercontent.com/299357/235310878-bfb1f099-5ca3-4824-abd8-6bd660f46e8a.png)

**Comment by lenadelaloire** [comment]
Hi Dvanoni, thanks for your quick reply!
I do have APA 7th installed, and in fact, it is the only style I have
installed (I have deleted all others as it is the only one I use). Are all
of the other styles needed to make Notero link properly?
Let me know, and thank you again!

**Comment by lenadelaloire** [comment]
Aha! I took a look through #12 <https://github.com/dvanoni/notero/issues/12> -
my export preference was not set to anything. I also changed my language
from English - Canadian to English - US like your photo showed, just in
case.
Seriously thank you for this, it is amazing!

**Comment by dvanoni** [comment]
Good find! I'm glad you got it working! 🎉
