### ISSUE TITLE
Questions about reccommended workflow

### ISSUE THREAD

**Issue by victormnielsen** [dvanoni/notero#266]
Hello!

I would like some advice on the reccommended workflow from Zotero to Notion. 
1. I have 4 main folders in Zotero: Projects, Areas, Resources, and Archive. I would like to add all of these to Notion in the same database. It would be amazing if there was a new column for each level of subfolder that you can use to categorise things, where the column would contain the name of that subfolder
2. I am not sure what to do with tags. Am I able to add tags to Notion and have it back-sync?
3. Can I change the Status column to have other options?
4. I want to use notion to sort projects through my process of reviewing them. This process will sometimes eliminate a paper from a project. Is there an easy way to then take these "eliminations" and then move them in Zotero? 

A lot of these questions are in general related to how well the two databases relate. Whether it goes back and forth or not. 

Any help would be greatly appreciated. Also looking for tips on how you organise all this. 

Best regards
Victor

**Comment by dvanoni** [comment]
Hi Victor, thanks for your questions!

1. Notero syncs all items into the same database in Notion. In the Notero preferences within Zotero, you can select the folders (called "collections" in Zotero) that you want to sync—including any subfolders. Notero will sync the name of collections that your items are in as long as your Notion database contains a **multi-select** property named `Collections`. (The example databases linked from the readme have this property already.)
2. Unfortunately, the sync process only works from Zotero to Notion—not the other way around. See the [How to sync from Notion back into Zotero](https://github.com/dvanoni/notero#how-to-sync-from-notion-back-into-zotero) section in the FAQ for more info.
3. You can absolutely change the Status column however you please. It's not used by Notero itself, so it doesn't have any specific requirements.
4. Since we can't sync from Notion back to Zotero, there's not a way to automate this process. The best suggestion I have is to create some sort of filtered database view in Notion that can give you an easy way to reference the items you need to update in Zotero.

Truth be told, I personally don't handle research references, so I don't actually use Zotero myself. 😅 There are some guides made by other folks listed in the [Usage Guides](https://github.com/dvanoni/notero#usage-guides) section of the readme. You can also find other resources if you do a web search for "notion and zotero."

I hope this helps!
