### ISSUE TITLE
LibreWolf returns plugin corrupt

### ISSUE THREAD

**Issue by Lycophyta** [dvanoni/notero#267]
I am running LibreWolf 111.0-3, a fork of Firefox. I am receiving this output from Notero versions: 0.4.4, 0.4.5, 0.4.6. I have not found a version that installs correctly.

Any help you can provide would be much appreciated 👍 

![FaX8psLPmF](https://github.com/dvanoni/notero/assets/128862265/dc3afc06-09ed-41d2-a9c5-c7635af74d79)

**Comment by dvanoni** [comment]
Hi @Lycophyta, were you able to download and install the plugin? As mentioned in the [install](https://github.com/dvanoni/notero#install-and-configure-notero-plugin) steps of the readme, in Firefox-based browsers you'll need to right-click the download link and "save as" so that the browser doesn't try to install it into itself.

**Comment by Lycophyta** [comment]
Yes I was able to resolve my problem by reading the provided instructions
more closely. I had simply failed to read them carefully the first time,
naturally it took until after I had submitted my issue to realize my
mistake...

Thank you for inquiring.
