### ISSUE TITLE
notion database have Duplicate items

### ISSUE THREAD

**Issue by panyuz** [dvanoni/notero#27]
![截屏2022-01-06 上午11 33 07](https://user-images.githubusercontent.com/4372695/148324081-11b1624c-6aa3-4e48-a62a-e1d504715c97.png)

- checked "sync when items are modified"
- version:0.2.1
- Duplicate entries appear in the notion database when documents are moved into the watch folder

**Comment by dvanoni** [comment]
Thanks for reporting this, @panyuz. I have a few questions to help me narrow down the cause:

- If you modify an item in Zotero, does it create another duplicate in Notion, or does it update an existing one?
- Did you happen to delete the **Notion** link attached to the items in Zotero?
- Did you originally sync the items to a different Notion database, or have you always been using the same database?

**Comment by panyuz** [comment]
Zotero status:

- I have a folder named "privacy sens", which have 34 items. And all items were synced to notion.
- checked "sync when items are modified"
- version:0.2.1

> If you modify an item in Zotero, does it create another duplicate in Notion, or does it update an existing one?
 it update an existing one

> Did you happen to delete the Notion link attached to the items in Zotero?
Maybe. **I seem to have deleted the notion link for some entries. Not all entries in Notion are duplicated, so I think this should be the main reason for duplicate entries.** I will test more

> Did you originally sync the items to a different Notion database, or have you always been using the same database?
NO. I always sync to the same database.

**Comment by dvanoni** [comment]
Thanks for the additional info, @panyuz.

> Maybe. I seem to have deleted the notion link for some entries. Not all entries in Notion are duplicated, so I think this should be the main reason for duplicate entries.

I think this is likely the cause of the issue. The current implementation relies on those Notion links in order to keep track of which Notion page each Zotero item corresponds to. Without that link, Notero ends up creating a new page in Notion rather than updating the existing one.

Let me know if that seems to be what's happening for you!

**Comment by dvanoni** [comment]
From a [comment on #6](https://github.com/dvanoni/notero/issues/6#issuecomment-1018086346):

> if you add documents in bulk (5 entries), duplicate entries will still appear. I think it should be emphasized in the usage instructions to avoid such usage.

@panyuz would you mind sharing more about how you added these documents? Did you import 5 PDFs into Zotero? I'd like to see if I can recreate the issue to see if it can be solved. Thanks!

**Comment by domhicks** [comment]
has this been resolved? is there a way for Notion to check for duplicates in a database? thanks!

**Comment by dvanoni** [comment]
Hi @domhicks, can you share more about what you're encountering? Is Notero producing duplicate pages in your database? If so, does it happen consistently, or are there certain conditions under which duplicates are created? Thanks!

**Comment by domhicks** [comment]
Hi David,

I was just wondering if it is possible to have the notion database
recognize duplicates in a database so they can be deleted. Thanks!
ᐧ

Am Do., 13. Apr. 2023 um 07:00 Uhr schrieb David Hoff-Vanoni <
***@***.***>:

**Comment by dvanoni** [comment]
Hi @domhicks! I think it may be possible to build this. I've just pulled it out into a new feature request (#252) so I can keep track of it.

**Comment by jchutten** [comment]
Hi @dvanoni,

My Notero database also has duplicates. See below my answers to your questions:
If you modify an item in Zotero, does it create another duplicate in Notion, or does it update an existing one?
**It updates an existing one. Only one of the two get updated**
Did you happen to delete the Notion link attached to the items in Zotero?
**No I did not**
Did you originally sync the items to a different Notion database, or have you always been using the same database?
** Always to the same database**
![image](https://github.com/dvanoni/notero/assets/140513990/d817ba10-ee11-4275-9e32-12db612e0826)

Any idea how this is possible? Can I just delete the article that does not update when I change something in Zotero?
Also, I would also love a duplates identifier in Notero.

**Comment by dvanoni** [comment]
Hi @jchutten, thanks for sharing those details.

I'm not entirely sure how this happens. It could possibly be caused by some sort of network hiccup or a strange timing issue between when items are modified vs synced. Do you remember seeing any error messages as you were syncing items?

And yes, it should be safe to delete the pages in Notion that don't update when you change things in Zotero.

If I come up with an approach for detecting duplicates, I'll be sure to share an update in #252, so please follow along there.

**Comment by AblazeBoat1** [comment]
I've had a similar issue.

Each time that I add or edit a Zotero reference (e.g when typing a new note, adding a tag, or changing the name of a Zotero entry), Notero adds a duplicate notion database entry. Only the new, duplicate notion entry reflects the changes made to the zotero entry, while the original notion database entries remain the same. 

Is there any way to fix this?

Please see my answers to your previous questions below:
If you modify an item in Zotero, does it create another duplicate in Notion, or does it update an existing one?
**It creates another duplicate**
Did you happen to delete the Notion link attached to the items in Zotero?
**No I did not**
Did you originally sync the items to a different Notion database, or have you always been using the same database?
 **Always to the same database**

**Comment by dvanoni** [comment]
Hi @AblazeBoat1, thanks for reporting this! I looked into the issue and was able to reproduce it. It looks to be caused by a change that Notion recently made to how they return data.

I've documented this as a new issue for tracking purposes and will aim to get a fix released as soon as possible.

- #823

**Comment by dvanoni** [comment]
@AblazeBoat1, I've released [v1.2.3](https://github.com/dvanoni/notero/releases/tag/v1.2.3) that should fix the issue. Please check for updates in Zotero's plugins manager to install the update.

**Comment by AblazeBoat1** [comment]
Hi dvanoni,

Just checking through this now. I already had release v1.2.3 installed when the issue arose. Is there any other potential cause?

**Comment by dvanoni** [comment]
Thanks for following up, @AblazeBoat1. Are you saying with v1.2.3 installed you're still seeing the same issue with duplicate pages being created?

To help me debug, it would be great if you could send me a screenshot of the Zotero logs when you sync an item. See the below video for the steps to view the logs, and please be sure to expand the "Syncing item 1 of 1" line so that we can see the details of the Notion requests.

Thanks!

https://github.com/user-attachments/assets/062a8243-838d-4745-abb8-edc1743bfc8a
