### ISSUE TITLE
The Add-on isn't working in the Zotero 7.0.0 beta version

### ISSUE THREAD

**Issue by ExcitedAnt278** [dvanoni/notero#294]
**Describe the issue**
The Add-on can be installed and activated, but it doesn't show up in the Tools section. The sync items to Notion button is visible.

**To Reproduce**

1. Go to Zotero
2. Click on Tools
3. Scroll down to Manage Attachments
4. See error (Notero preferences is missing)

**Expected behavior**
Notero preferences should appear in the Tools menu after restarting Zotero.

**Screenshots**
<img width="373" alt="Screenshot 2023-07-25 at 12 24 35" src="https://github.com/dvanoni/notero/assets/30269290/79194dd5-129c-4436-ba9c-e7b21811c332">

<img width="179" alt="Screenshot 2023-07-25 at 12 26 47" src="https://github.com/dvanoni/notero/assets/30269290/5f46097f-4788-4695-9c50-6f949b7d9a57">

**Additional context**
Zotero v7.0.0-beta.23+fb5934563, Notero v0.4.7

**Comment by dvanoni** [comment]
Hi @ExcitedAnt278, thanks for reporting this. I've done some initial work to support Zotero 7, but there's still a little more to do before it will work correctly.

An important note with the changes is that the "Notero Preferences" option will no longer appear in the **Tools** menu. Instead, the Notero preferences will be available from Zotero's main preferences window. If you open that preferences window now, you may even see a "Notero" section on the side, but the content isn't loading right now due to #281.

**Comment by dvanoni** [comment]
Hi @ExcitedAnt278, I just released [version 0.4.9](https://github.com/dvanoni/notero/releases/tag/v0.4.9) which enables support for Zotero 7! Please give it a try and let me know if you run into any issues.
