### ISSUE TITLE
inline equation is not rendered in notion note 

### ISSUE THREAD

**Issue by sheldon123z** [dvanoni/notero#330]
**Describe the issue**
The note sync is good but some minor case is not fully solved, the inline equation is not rendered when sync the note from Zotero 7 to notion. The equation block is rendered perfectly. 

**Screenshots**
<img width="803" alt="image" src="https://github.com/dvanoni/notero/assets/42455304/2f1cebfb-c89b-4f39-b801-50501a13acbf">

**Comment by dvanoni** [comment]
Hi @sheldon123z, thanks for sharing this scenario.

Would you mind sharing the HTML for this Zotero note? I'd like to see if there's a recognizable way that inline equations appear in the HTML so that we can convert them into Notion as expected.

You can export an HTML file for a note like so:

https://github.com/dvanoni/notero/assets/299357/0138bcdc-140d-4ca9-980a-38e13f35c029

**Comment by dvanoni** [comment]
@sheldon123z, I figured out how to write an inline equation within Zotero, so I have what I need to work on this.

**Comment by dvanoni** [comment]
@sheldon123z, I just released [v0.4.12](https://github.com/dvanoni/notero/releases/tag/v0.4.12) with support for inline math expressions. Let me know if it's working for you!
