### ISSUE TITLE
Can't get sync of Notes working

### ISSUE THREAD

**Issue by programerkotik** [dvanoni/notero#350]
**I cannot set up synchronisation of Notes between Zotero and Notion**
I selected 'sync notes' in Notero preferences but the notes I create in Zotero don't appear in Notion. Any idea why?

**Comment by dvanoni** [comment]
Hi @programerkotik, thanks for reaching out.

It's admittedly not clear from within Zotero right now, but the note syncing feature is not yet automatic. Once you've enabled the option in the Notero preferences, you have to manually sync notes via the context menu on a note. Please see the [release notes for v0.4.8](https://github.com/dvanoni/notero/releases/tag/v0.4.8) for more details.

Let me know if it works for you!

**Comment by programerkotik** [comment]
I understand now! It works, but I expected the note to appear in the overview table. Great job anyway! Thank you!

**Comment by dvanoni** [comment]
I'm glad it's working!

You bring up a great point about the notes appearing in the table. I originally didn't explore that route because I was worried it could end up confusing if both regular items and notes were all displayed in the same table, but since I started work on the notes feature, Notion released new functionality in their databases to [allow sub-items to be added to a table](https://www.notion.so/help/tasks-and-dependencies). I'm going to explore this to see if it would provide a better solution than the current approach. Thanks for the idea, @programerkotik!
