### ISSUE TITLE
Database ID not found but everything follows the guidelines. 

### ISSUE THREAD

**Issue by Wei2624** [dvanoni/notero#410]
**Describe the issue**
Whenever I click the `sync to Notion`, the database ID not found error pops up. 

**Screenshots**
I linked my integration to the page. 
<img width="293" alt="image" src="https://github.com/dvanoni/notero/assets/6278809/0edabdc8-0909-4a29-a362-c5f329110e7c">

Database ID is copies from the following link:
`https://www.notion.so/Reading-List-d40ce6bf153e46b3843bf0532703476f?pvs=4`
as `d40ce6bf153e46b3843bf0532703476f`. 

The secret key is copied as well. 

Notion version: 3.1.0
Zotero version: 6.0.30
OS: Mac

Does anyone have an idea to solve this? Appreciated!

**Comment by dvanoni** [comment]
Hi @Wei2624! I'm not positive, but I'm wondering if you're encountering the same issue that was [described here](https://github.com/dvanoni/notero/issues/68#issuecomment-1569648241):

> I may have found the problem. In my case I copied the Notion page ID instead of the database ID. It appears that when you first create an empty page and then add a database to it, the IDs will be different. I got the database ID by copying a link to a specific view and then extracting the ID from the link. Now it works :)

It may be that you copied the link to a page with an _in-line_ database rather than a _full-page_ database. (See [Notion docs](https://www.notion.so/help/intro-to-databases#full-page-vs.-in-line-databases) for more details.) Notero requires the ID for the full database.

Let me know if this helps!

**Comment by Wei2624** [comment]
Hi @dvanoni , Thank you very much for the help. It actually works!

**Comment by dvanoni** [comment]
Great! Also, with Notero v0.5.7, the database ID field has changed from a text field to a dropdown selection that only lets you choose databases (rather than pages), so I'm hoping that will avoid this issue altogether.
