### ISSUE TITLE
issues with integrating v0.5.7

### ISSUE THREAD

**Issue by laurendudu** [dvanoni/notero#421]
**Describe the issue**
I tried installing the latest version of Notero, since I recently changed my laptop, however the "sync to Notion" button on Zotero was nowhere to be found. I thought it was maybe a syncing problem since I was changing my laptop, but after changing my notion integration and restarting my databse from A to Z it still did not show up. Then, I finally downloaded v0.5.6 and it worked like a charm. 
By looking at the latest release, the feature enhancement was supposed to be a dropdown for the db selection but I did not see that either. Am I missing something?

**To Reproduce**

1. [Download v0.5.7 of Notero](https://github.com/dvanoni/notero/releases/tag/v0.5.7)
2. Follow the Notero installation tutorial
3. See that the "sync to Notion" button does not appear when right-clicking items in Zotero

**Comment by dvanoni** [comment]
Hi @laurendudu, thanks for reporting this!

With v0.5.7, are you also missing the "Notero Preferences" item in the **Tools** menu? That's where the database dropdown should be.

I've seen similar issues when Notero encounters some sort of fatal error when it starts up.

Would you mind sending me a screenshot of the Zotero logs following these steps?

1. Install Notero v0.5.7, or if you already have it installed, please disable and re-enable it in the **Add-ons Manager**.
2. Open the Error Console from **Tools > Developer > Error Console**.
3. Scroll down to the bottom of the messages in the Error Console and take a screenshot.

We're looking for messages from Notero that hopefully look something like those in the screenshot below. If there's an error around there, that should hopefully point us in the right direction.

Thanks!

![CleanShot 2024-01-03 at 09 35 21@2x](https://github.com/dvanoni/notero/assets/299357/7448a37e-4885-4b51-b6ca-0c9719596592)

**Comment by laurendudu** [comment]
I do remember having the "Notero Preferences", however there was no dropdown.

When uninstalling the previous version and updating it to the newest v0.5.7, it seems to be working fine, at least in the interface. It looks like it retained the info (Integration token etc) from the previous version I had installed v0.5.6, and I can see the dropdown. Pehraps it was bugging the first time since there was no previous version of Notero on my computer? 

There is no error with syncing as well, checked on the console and I could only find this:
![image](https://github.com/dvanoni/notero/assets/60437222/85c37d53-6622-40d7-9752-0faeb5c8aa17)

**Comment by dvanoni** [comment]
Thanks for the update, @laurendudu. So just to confirm, automatic syncing seems to be working, but the "Sync to Notion" option still isn't available in the item menu?

If that's the case, we may only be able to see the errors in the logs when Notero first starts. I think it will be easiest to spot if you're able to do the following:

1. Disable Notero in the Add-ons Manager.
2. Open the Error Console and click the "Clear" button at the top.
3. Re-enable Notero.
4. Return to the Error Console but do not put `notero` in the Filter field because it may filter out any underlying error message.
5. Take a screenshot.

We should expect to see Notero's startup messages like in my previous screenshot, and if there's any error that occurs then I think we'll expect to see it around the line that says `[Notero] Starting UIManager`.

Thanks!

**Comment by dvanoni** [comment]
@laurendudu, are you still encountering this issue on the latest version of Notero?

**Comment by dvanoni** [comment]
I'm going to close this for now, but please feel free to reopen if needed.
