### ISSUE TITLE
Disruption of Drag-and-Drop Feature During Notero Sync

### ISSUE THREAD

**Issue by nicolnt** [dvanoni/notero#457]
**Describe the issue**
During the syncing process of Notero, the drag-and-drop functionality in Zotero becomes blocked, disrupting my workflow. As I heavily rely on drag-and-drop to assign tags or move documents within collections, this interruption significantly hampers my efficiency.

**To Reproduce**
Steps to reproduce the behaviour:

1. Add a tag by drag-and-drop or move document in a collection where Notero sync is enabled
2. Wait for Notero to stop syncing
3. Repeat step 1.
4. Step wait for the repeat of step 2. to finish
5. Again, for all the files you need to move or tags you need to add.

**Expected behavior**
Non-blocking dragging of file when Notero is syncing 

**Screenshots**
![image](https://github.com/dvanoni/notero/assets/12377588/07a9a4b2-e725-46c4-8571-d82e3498d932)
The screenshot shows Notero's small pop-up in the bottom-right corner of the Zotero window. During its display, drag-and-drop operations are inhibited, causing inconvenience.

**Additional context**

- Windows 10 Pro 22H2
- Zotero 6.0.30
- Notero 0.5.13

**Comment by dvanoni** [comment]
Thanks for reporting this, @nicolnt. I'm able to reproduce the behavior on macOS 14.2.1 in both Zotero 6.0.30 and Zotero 7.0.0-beta.56.

It's quite noticeable while trying to perform drag-and-drop operations, and I've also noticed that most UI interactions seem to be negatively impacted while a sync is in progress.

Upon some initial exploration, it looks like the UI impact occurs while Notero is performing operations to update Zotero items after each is saved to Notion. I imagine this is because these operations are happening on the main thread that's also used for UI updates.

I'll dig into this and see if I can come up with a fix.

**Comment by dvanoni** [comment]
I'm [discussing this](https://groups.google.com/g/zotero-dev/c/idY0PmyUrk4) with other Zotero developers on the mailing list. I don't have a solution yet, but I've at least narrowed down the cause to the code that generates item citations.

While absolutely not ideal, a way to work around the issue is by removing anything related to citations. Specifically, this means you'd have to:

- Delete the `Full Citation` and `In-Text Citation` properties from your Notion database (if you have them)
- In the Notero preferences, change the **Notion Page Title** setting to either `Item Title`, `Item Short Title`, or `Item Citation Key` (if you have Better BibTeX installed)

**Comment by dvanoni** [comment]
@nicolnt, I think I've hopefully fixed (or at least improved) this in [version 0.6.2](https://github.com/dvanoni/notero/releases/tag/v0.6.2).

The issue is indeed caused by the generation of citations, and it seems to be an issue that Zotero also suffers from when using its Quick Copy functionality—see [this Zotero forum post](https://forums.zotero.org/discussion/113721/zotero-7-beta-time-delay-when-doing-a-drag-and-drop-of-an-item).

It turns out that some citation styles cause more of a performance impact than others, and the APA style seems to be especially bad. Unfortunately, Notero used the APA style to generate author-date page titles, but that's no longer the case in v0.6.2.

There will still be a performance impact if using the `Full Citation` and `In-Text Citation` properties in combination with certain Quick Copy formats, but since the problem exists in Zotero itself, I don't know that I can easily fix it.

Please let me know if you're still having performance issues!

**Comment by dvanoni** [comment]
I'm happy to report that the underlying performance issue in Zotero has been fixed in https://github.com/zotero/zotero/pull/5399, which is available in the latest Zotero 7 beta. I've tested Notero using the APA style and can confirm that the performance issue is resolved!
