### ISSUE TITLE
Join attachment

### ISSUE THREAD

**Issue by sebastien835** [dvanoni/notero#47]
Hello,

Thank you so much for this work that is really helpfull!

I  have some question about PDF integration and i would like to be able to do one of these:

1. I would like to know if there is a way to import pdf attached in zotero directly in notion so i can have an access on my tablet/phone from notion?
2. Is it possible to transform the "File Path" column to a direct link on the file in my laptop? (i would like to just have to click on it to access the file)

Thank you by advance,

Seb

**Comment by dvanoni** [comment]
Hi @sebastien835, thanks for the feedback!

Unfortunately, neither of these options is currently possible because of limitations with Notion. These same issues were discussed in https://github.com/dvanoni/notero/issues/9#issuecomment-962534885, but to summarize here:

1. The Notion API [does not currently support uploading files](https://developers.notion.com/reference/file-object#externally-hosted-files-vs-files-hosted-by-notion).
2. Notion only supports `http:` and `https:` URLs, so it's not possible to link directly to the file using a `file:` URL. I've reached out to Notion to try to find out if they'll add support for `file:` URLs in the future.

In https://github.com/dvanoni/notero/issues/9#issuecomment-962579162, @hengfei-wang mentioned that they had a shortcut in [Alfred](https://www.alfredapp.com/) to open a file from selected text. Maybe that could be a workaround you could use?

**Comment by dvanoni** [comment]
Closing this issue as the above explanation was added to the README in 35208c10e7a4eb19d450b074b176bcf574486d7b.
