### ISSUE TITLE
Database in Notero Preferences not fillable

### ISSUE THREAD

**Issue by RicMlg** [dvanoni/notero#477]
**Describe the issue**
Hi, I'm trying to enter my database reference, but it won't let me do it. I only get the V shown in the image, what am I doing wrong? Greetings. 

**To Reproduce**

1. Go to 'Zotero -> Tools -> Notero preferences
2. Click on 'database'
3
<img width="664" alt="Screenshot 2024-02-28 at 10 45 30 PM" src="https://github.com/dvanoni/notero/assets/161674536/c59f6eec-4b5b-47e6-9f93-743b2a3a2e39">
. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dvanoni** [comment]
Hi @RicMlg, thanks for reporting this. I don't think I've seen this exact behavior before.

If Notero isn't able to find your database, it's supposed to show an error message and that dropdown should be disabled. However, it looks like in this case it has found a database but maybe can't display the name for some reason.

What is the name of your database in Notion?

If you try to sync an item by right-clicking it and selecting "Sync to Notion," do you see an error message or does it sync successfully?

**Comment by RicMlg** [comment]
Hi! And first, thanks for this amazing tool!! 
When a sync to Notion it works! one by one. But it has to be manually. What I don´t understand is, I never registered the dataset number in notero settings... I added the "integration token" but never the database... that's extrange.

**Comment by dvanoni** [comment]
@RicMlg, this does sound strange. Can you perform the following steps to see if your database ID did indeed get stored into Notero?

1. Open **Tools → Developer → Run JavaScript**
2. Paste the below code
    ```js
    Zotero.Prefs.get('extensions.notero.notionDatabaseID', true);
    ```
3. Click the **Run** button at the top left

If the database ID is stored, then it should appear on the right side of the window. Do you see that? If so, Notero has the database ID but can't display the name of the database for some reason.

**Comment by RicMlg** [comment]
Hi! It works, but it shows a completely different database number than I
have, but it works!I don't understand anything.
Maybe using the integration tokens is enough to connect zotero and notion?
The target database works perfectly!

Thanks again




ricardocampos.es
neurona.top

**Comment by RicMlg** [comment]
Hi! It works, but it shows a completely different database number than I have, but it works!I don't understand anything. 
Maybe using the integration tokens is enough to connect zotero and notion? The target database works perfectly!

Thanks again

**Comment by dvanoni** [comment]
I don't understand either! 😅 I wonder if it's perhaps related to _in-line_ vs _full-page_ databases as discussed in #410.

If you connected Notero to a page with an in-line database, that page would have a different ID than the database itself. But, Notero can still access the database because Notion provides access to everything that's a descendent of the page that's connected.

I'm still stumped about the blank dropdown, too. Maybe the database itself doesn't have a name, and it could be hard to see that if it's being viewed as an in-line database.

Does that make sense at all?

If you want to share a screenshot of your database in Notion, I might be able to have a better idea of what's going on. But you certainly don't have to. If you're satisfied with how it's working right now, then we can call it good!

**Comment by RicMlg** [comment]
Exactly David! The database name was empty. 
FYI, I restarted Zotero and Notion and still the same thing, but it is working perfectly so problem solved! But if you need it more info for your own researching, please let me know. 

Thanks so much for your support. Hoping a sync between Zotero and Remarkable. It could be amazing! 

Ricardo.
