### ISSUE TITLE
APIResponseError: query failed validation.

### ISSUE THREAD

**Issue by kleosnike** [dvanoni/notero#487]
Hi, I tried to sync notero and I solved other errors using the forum. Unfortunately when I try to save a paper it now shows this error I am not able to find in the forum. 

<img width="262" alt="Screenshot 2024-03-15 at 10 00 07" src="https://github.com/dvanoni/notero/assets/163522809/a9d822a1-9743-4302-bc7a-a355a601fc8a">

**Comment by dvanoni** [comment]
Hi @kleosnike, thanks for reporting this. I thought this issue had been fixed in an earlier version of Notero.

Are you on the latest version (0.5.15)? If not, please update Notero and then go into the Notero preferences to select your Notion database again. If you do that, does it resolve the issue?

**Comment by dvanoni** [comment]
@kleosnike, are you still encountering this issue on the latest version of Notero?

**Comment by dvanoni** [comment]
Closing this for now. Please feel free to reopen if you're still encountering this issue.
