### ISSUE TITLE
hi, when I delete a item in zotero, but it is not deleted in the notion. what can i do for this issue?

### ISSUE THREAD

**Issue by soleded** [dvanoni/notero#50]
hi, when I delete a item in zotero, but it is not deleted in the notion. what can i do for this issue?

**Comment by dvanoni** [comment]
Hi @soleded, thanks for the question! Currently, you will have to manually delete pages in Notion because Notero does not yet support syncing the deletion of items from Zotero.

Some folks have been discussing approaches for adding this support in #46. I'm going to close this issue so we can keep all the discussion in #46. Please feel free to add your input there!
