### ISSUE TITLE
Add configurable options to import

### ISSUE THREAD

**Issue by mtillman14** [dvanoni/notero#52]
Hi,
First, thank you so much for this. It's fantastic! I wonder if it is possible to add a "Journal" field as a Select property and add the option to have the Authors as a multi-select? Also, if Author is a multi-select, can it be formatted as "Last Name, First Name" (or first initial)? That will help distinguish authors from one another if they are in a multi-select property.

I previously had been importing from Zotero into Notion manually to analyze who my most-cited authors are and which journals they publish. For that, selects and multi-selects are ideal. But I know that some people will want these properties to be Text. Can this be configurable?

Thank you!

**Comment by dvanoni** [comment]
Hi @mtillman14, thanks for the feedback!

I think using multi-select for these fields is an interesting idea and could unlock additional workflows in Notion as you mentioned. I believe this should be technically possible, and I agree that it'd be good to make it configurable. I'll add this to the backlog.

**Comment by VDimovaEdeleva** [comment]
Hi @dvanoni, 

Thank you also from my side for this amazing tool. 
I would like to suggest, if possible, to also export the "Publication" field from the Zotero info as select property. 

 Thanks!

**Comment by russ-mcbride** [comment]
Fantasically useful tool, thanks! To the growing list of property requests, being able to pull Notes from Zotero would also be helpful. :-)

**Comment by dvanoni** [comment]
I'm glad you're enjoying it, @russ-mcbride!

Syncing notes is something I'm currently working on. You can follow the progress in #4.

**Comment by dvanoni** [comment]
Happy holidays! I've just released [v0.5.5](https://github.com/dvanoni/notero/releases/tag/v0.5.5) which adds support for syncing the following properties:

| Property Name | Property Type |
|--------|--------|
| `Date Modified` | Date |
| `Extra` | Text |
| `Place` | Text |
| `Proceedings Title` | Text |
| `Publication` | Text |
| `Series Title` | Text |

I still want to add support for customizing the properties that can be synced. I'm tracking that work in #355, so please follow along there if you're interested!

As for using **multi-select** instead of **text**, I'm also hoping to enable that with the same work. I'm tracking that in #146.
