### ISSUE TITLE
Linked notes don't sync

### ISSUE THREAD

**Issue by AntheaLiles** [dvanoni/notero#528]
Syncing do not work on items with a note (Zotero 7)

![image](https://github.com/dvanoni/notero/assets/120063455/646484a9-8990-4334-bed6-e921f9980a55)

This "contents" note is generated automatically by Zotero,
Maybe I would prefer to just remove them... In the mean time, Notero seems to be unable to sync this item

**Comment by dvanoni** [comment]
Hi @AntheaLiles, thanks for reporting this.

I believe you're encountering the same issue reported in #463 which is due to the fact that the Notion API only allows a certain level of nesting when sending content to it. Until we come up with a more robust solution, notes with deeply nested bulleted/numbered lists will encounter this error.

Does that sound like it describes your issue?

**Comment by AntheaLiles** [comment]
Hi dvanoni,

Thanks for your answer,

Yes, it seems that it's the real issue behind the scene
So, as I've thought about, I will just remove these "content" notes as I don't use them.

Thanks again for your help

Oh and, maybe a lil feature request as I'm typing, 
If you could provide a "sync all" button on the setting panel to resync all selected collections 
It will be really appreciated
