### ISSUE TITLE
auto sync not working

### ISSUE THREAD

**Issue by l0wbird1337** [dvanoni/notero#579]
Hey,

I'm on a Mac with Apple Silicon and have Zotero 7.0.6 and Notero 0.6.3 installed. I'm using this Notion template: [Notion Template](https://woolly-apogee-7c0.notion.site/f7c25fe44dd946f0924ebbc3bdb2430a?v=4c5d5afbb44d40359c81ab8102a7faca). My items (papers) are in a Zotero Group library within a collection.

I can't get automatic syncing to work; it only syncs when I manually click "Sync to Notion" on a paper. What could be the issue?

**Comment by dvanoni** [comment]
Hi @l0wbird1337, thanks for reaching out.

Does the collection show up in the Notero preferences, and are you able to enable sync for it?

If sync is enabled as expected, could you make an edit (such as adding a tag) to an item in the collection and then post a screenshot of the error console so that we can see if there are any errors occurring?

Below is a video that shows confirming the collection has sync enabled and then opening the error console to confirm the item syncs successfully when a tag is added to it.

https://github.com/user-attachments/assets/ef6e712b-10aa-4b86-91b5-f64b2a7d5d92

**Comment by l0wbird1337** [comment]
nevermind, turns out i was not familiar with the difference between a library and a collection. Also had two libraries/ collection with same naming which caused confusion. 
everything works now, sorry for the trouble, great help!
