### ISSUE TITLE
Error in XPI installation on Firefox

### ISSUE THREAD

**Issue by shoyip** [dvanoni/notero#597]
**Describe the issue**
Instead of the installation of the Firefox plugin I get an error message saying: Impossible to download plugin since the file seems damaged.

**To Reproduce**

1. Go to the repository
2. Click on the link of the xpi file
3. Get the message

**Expected behavior**
Successful installation of plugin.

**Screenshots**

![immagine](https://github.com/user-attachments/assets/941ee611-0cbc-4392-ac9f-eab0c317bb02)

**Additional context**
I am using Zotero 7, Firefox v 131, on Archlinux.

**Comment by dvanoni** [comment]
Hi @shoyip, in Firefox you'll need to right-click the download link and choose **Save Link As...** in order to properly download the file. Let me know if that works for you!

**Comment by shoyip** [comment]
Hi! I've tried that as well. I always get the same result, even if I open the xpi from the file manager or the download section.

**Comment by dvanoni** [comment]
Ah, if you're trying to open the xpi file directly that won't work because Firefox will try to open it. You need to open Zotero's Plugins Manager from the Tools menu and then install the plugin either using the gear menu or dragging and dropping the xpi file.

Does this work for you?

https://github.com/user-attachments/assets/8f6b2746-167b-4460-b0f5-f4b6436e41e8

**Comment by shoyip** [comment]
Right! It works, I have completely missed the point that it was a plugin for Zotero and not for Firefox. Thank you! I think it could be nice to specify it in the README just for the distracted people like me 😅 thanks again!

**Comment by shoyip** [comment]
Don't bother it's already written... sorry for the confusion.
