### ISSUE TITLE
No warning and doesn't work. 

### ISSUE THREAD

**Issue by SedVi** [dvanoni/notero#60]
Hello, I installed the plugin on zotero and did the operations specified from the notion. But no content is transferred to notion. There is no message in the form of a warning. Another situation I would like to point out is about the database-id, which consists of 36 characters. When I copied the invite link over Notion, the databse id in the part you specified consists of 32 characters. I tried again and again by watching the video below to establish the connection, but it didn't work.

https://www.youtube.com/watch?v=8IC8-mPbjCo&t=2s&ab_channel=HollyJane

**Comment by sanhe374** [comment]
I also have the same issue that nothing is being transferred from Zotero to Notion and the database ID contains 32 characters only.

**Comment by dvanoni** [comment]
@SedVi @sanhe374, thanks for reaching out!

You bring up a good point about the database IDs. The IDs are [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format), so their "full" format is 36 characters of the form `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`. Notion usually omits the hyphens (as you can see from the link you copied), so you end up with 32 characters. According to their documentation, both the hyphenated and un-hyphenated IDs shoud work. I'll update the README to make this more clear.

And thanks for sharing that video! I had no idea it existed! I noticed someone in the comments seemed to be running into a similar issue, and I wonder if you're encountering the same thing. It sounded like they configured everything but nothing happened, and I believe that's because the sync will only occur when items are added to or modified within a synced collection as described in the [How Notero Works](https://github.com/dvanoni/notero#how-notero-works) section of the README.

The solution for them was to create a new collection in Zotero, configure the Notero preferences to sync it, and then move items into that collection. Another way to solve this is by adding a temporary tag to items as [described in the README](https://github.com/dvanoni/notero#how-to-bulk-sync-existing-items).

Please let me know if one of those approaches gets things working for you!

**Comment by SedVi** [comment]
Thank you very much for your return. I tried the last method you mentioned and it worked. Now I can export data to notion. This made my work very fast :)

**Comment by gregdyche** [comment]
I found my two mistakes that caused me the same trouble - no warning and no sync. 

1. I went to Zotero's main preferences and had no idea what 'enter the required preferences.' meant.  Was clearly my mistake since you said Tools - Notero Preferences, but I just skipped right over that and when to Zotero - Preferences.
2. I didn't have a collection yet in Zotero. I'm new to the tool. I had a dozen or so sources just in 'My LIbrary'. I had to create a collection, and I could then select a collection to sync in Notero Preferences. 

Still isn't working yet, but I'm getting an error now instead of nothing. :)
