### ISSUE TITLE
.xpi file corrupt/incompatible with FireFox

### ISSUE THREAD

**Issue by CassieConnected** [dvanoni/notero#61]
Unable to add .xpi to FireFox add-ons per https://jsrepos.com/lib/dvanoni-notero instructions
When .xpi file drag/dropped to add-ons, FireFox will not add it. An error message saying the file is corrupt appears.
I am using up-to-date FireFox version 99.0.1

**Comment by Atif-Anwer** [comment]
You need to install the xpi in Zotero (Open the Zotero Add-ons Manager via the Tools → Add-ons menu item.
) and not in Firefox.

**Comment by dvanoni** [comment]
@CassieConnected, the page you linked appears to have an outdated version of the README. I'd suggest viewing the README directly here on GitHub to ensure you're looking at the latest version. The current version of the [installation instructions](https://github.com/dvanoni/notero#install-and-configure-notero-plugin) has a note about how to download the `.xpi` file with Firefox since, by default, Firefox itself tries to install the plugin. @Atif-Anwer is correct that you want to download the file first and then install it in Zotero as directed.

Let me know if you're still having trouble with it!

**Comment by CassieConnected** [comment]
@Atif-Anwer @dvanoni thank you both so much for your helpful answers and patience with an (extremely) novice/inexperienced user!
