### ISSUE TITLE
"Database: To Read" The ID cannot be inserted

### ISSUE THREAD

**Issue by ecofriiendly** [dvanoni/notero#616]
In Zotero settings, I can type the integration token in; however, I cannot paste the database ID because the section to insert the ID number is not enabled. Instead, there is a list view where only the "To Read" option is available.

I did create an integration and connected it to my desired database on Notion. I don't know why Zotero doesn't allow the ID insertion option.
![notero](https://github.com/user-attachments/assets/60f06360-02c4-46bf-ac03-de477ff57d50)

**Comment by dvanoni** [comment]
Hi @ecofriiendly, Notero now allows you to select from a dropdown of your connected databases instead of having to manually copy and paste a database ID. If that "To Read" database is the one you want to use, then you should be all set!

Can I ask which instructions you were following that told you to paste the database ID? Notero hasn't required pasting the ID since version 0.5.7 which was released back on the first day of this year.

**Comment by ecofriiendly** [comment]
Hi there! Wow, yes, this is a very straightforward solution. It is working.

I was following the video guidelines below, which were actually very helpful, except for this point.

[How To Sync Zotero → Notion // Research Paper Workflow (2023 Tutorial)](https://youtu.be/8RFFxFcrLCo) (video) by [Holly Jane](https://hollyjane.org/)
[Smart notetaking by starting with integrating Zotero and Notion: A first step](https://youtu.be/4Z_5tskdNsY?t=1173) (video) by [Dr. Jingjing Lin](https://jingjing-lin.com/)

Bests!

**Comment by dvanoni** [comment]
I'm glad it's working!

Thanks for sharing which videos you were referencing. I know those are linked in the README, so I think I should add a note that they have some outdated information. Technology moves fast! 😄
