### ISSUE TITLE
API Response Error: Invalid request URL

### ISSUE THREAD

**Issue by GFirmer** [dvanoni/notero#62]
Hi, 
I'm super excited to use this integration but I keep getting this error and nothing syncs to my Notion database. I am pretty sure I've followed the setup instructions to a tee. Any help would be appreciated - thank you!

![Screen Shot 2022-04-21 at 10 18 25](https://user-images.githubusercontent.com/68259575/164345065-87197ecb-0b10-4ec6-a5f2-fa9245b21196.png)

**Comment by dvanoni** [comment]
Hi @GFirmer, thanks for reaching out!

I can't say that I've seen this specific error before, so I'm wondering if you could send me a screenshot of the error logs? You can view the logs in Zotero by going to **Tools > Developer > Error Console**. Once you're there, click the **Clear** button at the top to get a clean slate, and then try an action to trigger the sync again.

Hopefully the logs will have some more details to help us figure this out!

**Comment by GFirmer** [comment]
Hello! Thanks for your help; here is what the error console is showing:

![Screen Shot 2022-04-21 at 16 13 34](https://user-images.githubusercontent.com/68259575/164386221-5bcc553c-19d5-457e-93e2-69691ccb6f61.png)

**Comment by GFirmer** [comment]
![Screen Shot 2022-04-21 at 16 19 23](https://user-images.githubusercontent.com/68259575/164387014-ac82363a-95a9-4226-8ca9-ebb715525edb.png)

On the second try some more info that may be helpful?

**Comment by dvanoni** [comment]
@GFirmer thanks for that incredibly fast reply! 🤩

I remember seeing errors similar to those `NS_ERROR` ones when I was developing things, but I don't think I've seen it come up in a published version of the plugin before. I'll have to dig into that a bit more...

Your second message has the logs I was expecting to see. I was hoping those would have a bit more detail, but it looks like all it gives us is the same invalid URL message. I should improve those to actually include the URL! 😅 

So since we don't have that URL right now, could you provide me some other info?

- What version of Zotero are you on?
- What other plugins do you have installed, if any?
- Would you mind pasting the **Database ID** field from the Notero preferences?

Thanks!

**Comment by GFirmer** [comment]
@dvanoni  I'm on Zotero 6.0.4 and these are my other add ons:
![Screen Shot 2022-04-21 at 16 39 48](https://user-images.githubusercontent.com/68259575/164389965-339b3aef-d8ee-4bfd-b3b9-f7dac4baa8cd.png)

This is the Database ID: https://www.notion.so/chem-ed-doctorate/d04f3515577249c9acc64734396e415a?v=7de788de32e74cbb91ef5f842179ca58

**Comment by dvanoni** [comment]
Ah, I think that's it! For the database ID, you want to pull out just the ID part of that full URL as described in step 4 of the [Configure Notion](https://github.com/dvanoni/notero#configure-notion) section of the README.

In your case, it would be just `d04f3515577249c9acc64734396e415a`. Try putting just that in the Notero preferences and see if that works for you!

**Comment by GFirmer** [comment]
Heyyyy! I was so worried it would be a silly user error - I obviously skimmed those instructions! Thanks so much for your help :) Enjoy the rest of your day

**Comment by dvanoni** [comment]
Glad it's working for you! I hope it proves useful!
