### ISSUE TITLE
API Response Error: can't update a page that is archived

### ISSUE THREAD

**Issue by angelo-sotto** [dvanoni/notero#74]
Hi! Thank you so much for this. I am running into an API response error syncing my items from Zotero into notion, have attached a screenshot:

<img width="279" alt="Screen Shot 2022-05-11 at 11 28 50 AM" src="https://user-images.githubusercontent.com/105378708/167895555-e817a385-151f-4347-a06e-93ca32acb6d0.png">

The main issue is that the database (set up as a full page) that I am syncing to is not archived as far as I know - I wasn't even aware that Notion had an archive feature. I've tried to troubleshoot this by creating a new database to sync into, re-doing the process of adding the plug-in on Zotero, but still receive the same error every time. Syncing did work the very first time that I tried it but it has not worked since.

Any tips on how I can further troubleshoot? Again thank you so much!

**Comment by dvanoni** [comment]
Hi @angelo-sotto! I've seen something like this before in #43.

I believe what's happening here is that one of your items did successfully sync into Notion at some point, but that page in Notion has since been deleted. The thing to note about deleting pages in Notion is that they go into the Trash, and this is what the API refers to as "archived."

When Notero successfully syncs a Zotero item, it adds a link attachment to it named `Notion`. This is used to associate the item in Zotero with the page in Notion so that any future updates to the item will attempt to sync to the same page in Notion (rather than create a new page). However, if that page has been deleted, I think it will cause the error you're running into.

All that being said, I think the way you may be able to solve this is by deleting the `Notion` link attachment on any Zotero items that are giving you trouble. This should cause Notero to create new pages in Notion rather than try to update the deleted pages.

The below screenshot shows an example of the link I'm referring to. Let me know if this helps!

![CleanShot 2022-05-11 at 21 42 00@2x](https://user-images.githubusercontent.com/299357/167993648-781ec4c7-92c9-48a1-a5d7-382e9bd15cbf.png)

**Comment by angelo-sotto** [comment]
Worked perfectly - thank you for the fix and for this amazing tool :)
