### ISSUE TITLE
Would Notero work across two computers that share the same Zotero library?

### ISSUE THREAD

**Issue by amyhdt** [dvanoni/notero#80]
I have two laptops that use the same Zotero library, which syncs across one drive. Could I add Notero to both? I'm scared to try in case it messes something up. Also, thanks for making this - it's so useful!

**Comment by dvanoni** [comment]
Hi @amyhdt, thanks for the interesting question! I haven't considered this use case before.

In theory, I believe this should work. I think the most critical piece is that you'll want to ensure the "Notion" link attachment on your Zotero items are being synced between your two laptops. Notero uses that to ensure that multiple syncs of the same Zotero item will update the same page in Notion rather than creating a new page each time.

![CleanShot 2022-05-26 at 22 00 13@2x](https://user-images.githubusercontent.com/299357/170632812-637711ed-8f3c-4ac8-93d2-73c820a11d9a.png)

If you want to do a "safe" test, I think you could try the following:

1. On the first laptop:
   1. Create a new collection in Zotero.
   2. In the Notero Preferences, enable syncing for just that one collection.
   3. Add a single item into the collection.
   4. Ensure the item syncs into Notion and the "Notion" link is attached to the Zotero item.
2. On the second laptop:
   1.  Ensure Zotero has synced the collection, item, and "Notion" link.
   2. If the above is true, enable the same Notero Preferences.
   3. Update the item and see if it updates the page in Notion rather than creating a new page.

With the above test, I think the worst that could happen is you'll end up with a duplicate page in Notion, which should be safe to delete. But hopefully it all works as expected! I'm really curious to hear how this goes if you give it a try!

**Comment by dvanoni** [comment]
@amyhdt were you ever able to try using Notero across two computers? If so, did it work?

**Comment by amyhdt** [comment]
@dvanoni, I have to say I forgot about this, but I just tried it out now and it seems to be working! From the 2nd laptop, I added a new item fine, and also added a tag to an existing item in the synced collection, and it updated the Notion database item. So far, so good! Thanks for your help.

**Comment by dvanoni** [comment]
@amyhdt, thanks for following up. That's great to hear! Of course, please let me know if you do run into any issues at some point.
