### ISSUE TITLE
attachment label for items

### ISSUE THREAD

**Issue by fredericky123** [dvanoni/notero#81]
Usually, I used the attachment label of items to check which item does not have pdf attachments, then I will download the pdf files manually. However, since each item has notion attachments, I cannot figure out which item doesn't have pdf directly.

Can we set settings exclude the attachment monitoring for notion attachments?
<img width="479" alt="image" src="https://user-images.githubusercontent.com/13982749/170913586-b4a1439b-9d9b-4a75-a64e-4d052b6dcdf6.png">

**Comment by dvanoni** [comment]
Hi @fredericky123, as discussed in the [How Notero Works](https://github.com/dvanoni/notero#how-notero-works) section of the README, the "Notion" attachment serves as a reference for Notero so that it can update existing pages instead of creating duplicate pages for a given Zotero item. Because it's a key component of how Notero works, I don't believe we'd be able to easily remove it.

Would you be able to use the "Attachments" column for your purposes? I believe it should show which items do or do not have PDFs.

![CleanShot 2022-05-29 at 21 26 29@2x](https://user-images.githubusercontent.com/299357/170917221-4af284b9-e9fc-4a42-825c-6478adfd09d8.png)

If this column isn't visible, you should be able to enable it by right-clicking on the columns.

**Comment by fredericky123** [comment]
Oh, yeah, this is a great idea! Thanks a ton! I even didn't realize that.
