### ISSUE TITLE
creat a panel according to the tags

### ISSUE THREAD

**Issue by fredericky123** [dvanoni/notero#83]
Since tags in Zotero can sort out the items with specific tags, can we also use tags in Notion to sort out the items?
This may be related to https://github.com/dvanoni/notero/issues/30

**Comment by dvanoni** [comment]
@fredericky123 you can absolutely use tags for this! I think it's a great use case for them. Notero supports syncing tags if you add a **multi-select** property named `Tags` to your Notion database.

The approach for collections discussed in #30 is a bit different because there's some more nuance to collections than tags. But, the general idea of using them to categorize your items would be similar.

Did you have a specific issue you needed help with regarding tags?

**Comment by fredericky123** [comment]
Great! I was not familar with Notion, but now I know how to filter accorting to the tags with your notice!
Thanks a ton fot the notice!
