### ISSUE TITLE
can we go back to "Literature review" part from specific item page?

### ISSUE THREAD

**Issue by fredericky123** [dvanoni/notero#85]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/13982749/171376248-9087663a-c419-4663-917d-62211a94daa2.png">
I want to switch from the item specifications to it in the "literature review" part, can we? From above picture to below picture
<img width="767" alt="image" src="https://user-images.githubusercontent.com/13982749/171376606-87a8a90f-05e3-4da6-b311-75597c9643fa.png">

**Comment by fredericky123** [comment]
we have "open" option in the below picture, can we have "back" option in the above picture?
Thanks  a ton!

**Comment by dvanoni** [comment]
@fredericky123 I'm not sure if I'm exactly understanding your question. If you're asking about navigating in Notion from a database page back to the database itself, I think you should be able to do so by clicking on either the database name or the back button (whether in the Notion desktop app or in your web browser). Please let me know if you're asking about something else!

![CleanShot 2022-06-01 at 21 43 54@2x](https://user-images.githubusercontent.com/299357/171554889-738afe79-4ebc-4012-970d-6725509dfdb3.png)

**Comment by fredericky123** [comment]
Thanks @dvanoni , going back to the database itself is part of my expectation, I also want to go back to the specific item location of the database since I have a lot of items in the database.
![image](https://user-images.githubusercontent.com/13982749/171558559-432572d3-32d2-48d3-b024-b92ff6c36a91.png)

**Comment by dvanoni** [comment]
@fredericky123 ah I see what you're asking. To be honest, I'm not quite sure how to achieve that. This is something specific to Notion rather than Notero, so I'd recommend reaching out to them using the help widget in the bottom right corner.

I'd be curious to hear what you find out!

![CleanShot 2022-06-02 at 00 40 02@2x](https://user-images.githubusercontent.com/299357/171579564-4c74169f-3981-4ec1-8652-60e71d295ec4.png)

**Comment by fredericky123** [comment]
Thanks so much!
