### ISSUE TITLE
Zotero not letting me give permissions

### ISSUE THREAD

**Issue by juliagorman** [dvanoni/notero#91]
I correctly added my integration token and database ID as described in the README and various videos into Zotero after adding the Notion plugin. However, it still isnt syncing after i finish this final step as there is no button to click 'ok' on Zotero and this button is present on the videos I have been watching. 

I have tried restarting both Notion and Zotero as well as deleting the both plug in from both applications and it still doesnt work.  

<img width="785" alt="Screen Shot 2022-07-19 at 11 13 14 AM" src="https://user-images.githubusercontent.com/32439305/179821810-57dd2c69-05f7-4296-9ae8-c6efbcb7d1b6.png">

I have attached a screenshot for clarity.

**Comment by dvanoni** [comment]
Hi @juliagorman, thanks for reaching out!

The presence of the "OK" button here is actually a configurable setting in Zotero*, and it applies to Zotero's own preferences window as well. I think it might have a different default value on different platforms (e.g. Mac vs Windows), which is why you may see the "OK" button show up in some videos. Even if the "OK" button isn't there for you to click, your Notero preferences _should_ still be saved. You can confirm this by closing the **Notero Preferences** window, opening it back up, and ensuring that everything you entered is still there.

That being said, Notero does not automatically start syncing once you configure it. In order to sync items, you either have to add a new item or modify an existing item in one of your monitored collections. I know this isn't ideal, and I hope to eventually improve this process. In the meantime, I've provided a workaround described in the [How to bulk sync existing items](https://github.com/dvanoni/notero#how-to-bulk-sync-existing-items) section of the README.

Does that sound like it would solve things for you? Let me know!

---

\* If you want to change it, you can do so by opening Zotero's preferences, navigating to the **Advanced** tab, clicking the **Config Editor** button at the bottom, searching for the `browser.preferences.instantApply` preference, and then toggling its value from `true` to `false`.
